replicaCount: 2

image:
  repository: igorkar/node-hostname
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: LoadBalancer
  port: 3000

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
