name: Build and push Docker image

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER_NAME: demo

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: DockerHub login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.0.0
      with:
        push: true
        tags: igorkar/node-hostname:${{ steps.commit.outputs.short }}
    
  deploy: 
    needs: build

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      
    - name: Deploy to EKS
      env:     
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        helm upgrade node-hostname ./helm/ --values ./helm/values.yaml --set image.tag=$IMAGE_TAG